# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Model\AdventureLabApiClient:
        class: App\Model\AdventureLabApiClient
        arguments:
            $consumerKey: '%env(CONSUMER_KEY)%'

    App\Model\ExportGenerator:
        class: App\Model\ExportGenerator
        arguments:
            $cacheDir: '%env(resolve:CACHE_DIR)%'
            $cacheTtl: '%env(CACHE_LIFE_TIME_IN_SECONDS)%'

    App\Model\AdventureLabDatabase:
        class: App\Model\AdventureLabDatabase
        arguments:
            $dataDir: '%env(resolve:DATA_DIR)%'
